server {
    listen 80;
    server_name jenkins.example.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name jenkins.example.com;

    ssl_certificate /etc/nginx/certs/jenkins/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/jenkins/privkey.pem;

    client_max_body_size 1G;

    location / {
        proxy_pass http://jenkins:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket 대응
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
