server {
    listen 80;
    server_name rundeck.example.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name rundeck.example.com;

    ssl_certificate /etc/nginx/certs/rundeck/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/rundeck/privkey.pem;

    location / {
        proxy_pass http://rundeck:4440;
       
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
